captainVersion: 4
services:
    $$cap_appname:
        caproverExtra:
            containerHttpPort: $$cap_APP_PORT
        restart: always
        ports:
            - $$cap_APP_PORT:$$cap_APP_PORT
        image: node:$$cap_NODE_VERSION
        commands:
            - 'apt-get install -y git'
            - 'npm install -g @quasar/cli'
            - 'git clone $$cap_APP_GIT_REPO ./'
            - 'quasar build -m spa'
        volumes:
            - $$cap_appname-data:/data
        environment:
            NODE_ENV: production

caproverOneClickApp:
    variables:
        - label: 'Node Version'
          description: Application version, currently latest to get the most current one
          defaultValue: 'latest'
          id: $$cap_NODE_VERSION

        - label: 'Port to open'
          description: Port to access the quasar pages
          defaultValue: '8080'
          id: $$cap_APP_PORT

        - label: 'Git repository'
          description: Git repository which will be cloned
          defaultValue: 'http://'
          id: $$cap_APP_GIT_REPO

    displayName: Quasar
    isOfficial: true
    description: A Vuejs framework using node.
    documentation: https://github.com/quasarframework/quasar
    instructions:
        start: |-
            A Vuejs framework using node.
            GitHub: https://github.com/quasarframework/quasar
        end: |-
            You're done! 😄

            Your service is available at http://$$cap_appname.$$cap_root_domain